### ISSUE TITLE
App crashes when enabling/disabling coins

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/bank-wallet-android#548]
Changing the list of coins (enabling, disabling, ordering) sometimes crashes app with Exception "tryGetViewHolderForPositionByDeadline", "Inconsistency detected. Invalid item position 2(offset:2).state:3".

Possible solution: https://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position

**Comment by abdrasulov** [comment]
It still crashes with Exception

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | length=1; index=-1
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
    at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
    at java.util.ArrayList.get(ArrayList.java:439)
    at io.horizontalsystems.bankwallet.modules.balance.BalanceModule$BalanceItemDataSource.setState(BalanceModule.kt:80)
    at io.horizontalsystems.bankwallet.modules.balance.BalancePresenter.didUpdateState(BalancePresenter.kt:75)
    at io.horizontalsystems.bankwallet.modules.balance.BalanceInteractor$onUpdateAdapters$$inlined$forEach$lambda$2.accept(BalanceInteractor.kt:83)
    at io.horizontalsystems.bankwallet.modules.balance.BalanceInteractor$onUpdateAdapters$$inlined$forEach$lambda$2.accept(BalanceInteractor.kt:11)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 9 more
```
