### ISSUE TITLE
App crashed while doing fetchRates()

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android#603]
```
io.horizontalsystems.bankwallet.dev.testnet E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-15
    Process: io.horizontalsystems.bankwallet.dev.testnet, PID: 16202
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | length=33; index=33
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=33; index=33
        at java.util.ArrayList.add(ArrayList.java:468)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsInteractor.fetchRates(TransactionsInteractor.kt:112)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsPresenter.fetchRatesForRecords(TransactionsPresenter.kt:122)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsPresenter.didUpdateRecords(TransactionsPresenter.kt:106)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsInteractor$onUpdateCoinCodes$$inlined$forEach$lambda$1.accept(TransactionsInteractor.kt:144)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsInteractor$onUpdateCoinCodes$$inlined$forEach$lambda$1.accept(TransactionsInteractor.kt:13)
```

**Comment by abdrasulov** [comment]
Fixed in #624
