### ISSUE TITLE
App crashed on Unlink

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android#616]
I had multiple ERC20 tokens enabled in wallet

```
Process: io.horizontalsystems.bankwallet.dev.testnet, PID: 28088
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1475)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1475)
        at io.horizontalsystems.ethereumkit.EthereumKit.clear(EthereumKit.kt:529)
        at io.horizontalsystems.bankwallet.core.managers.EthereumKitManager.clear(EthereumKitManager.kt:27)
        at io.horizontalsystems.bankwallet.core.managers.AuthManager.logout(AuthManager.kt:43)
        at io.horizontalsystems.bankwallet.modules.settings.security.SecuritySettingsInteractor.unlinkWallet(SecuritySettingsInteractor.kt:47)
        at io.horizontalsystems.bankwallet.modules.settings.security.SecuritySettingsPresenter.confirmedUnlinkWallet(SecuritySettingsPresenter.kt:44)
        at io.horizontalsystems.bankwallet.modules.settings.security.SecuritySettingsActivity.onConfirmationSuccess(SecuritySettingsActivity.kt:133)
        at io.horizontalsystems.bankwallet.ui.dialogs.BottomConfirmAlert$onCreateDialog$1.onClick(BottomConfirmAlert.kt:48)
        at android.view.View.performClick(View.java:6303)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Dianaaiym** [comment]
When enable ERC 20 tokens in wallet, i can not unlink from this device. After Unlink seeing Unlock Screen
