### ISSUE TITLE
App crashed while trying fetching many rates at the same time

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/bank-wallet-android#805]
Crash log:

```
OkHttp: <-- HTTP FAILED: java.net.SocketException: socket failed: EMFILE (Too many open files)
2019-04-10 16:39:17.059 W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
2019-04-10 16:39:17.060 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-04-10 16:39:17.060 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-04-10 16:39:17.060 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-04-10 16:39:17.062 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-04-10 16:39:17.064 W/System.err: Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
2019-04-10 16:39:17.064 W/System.err:     at android.database.CursorWindow.<init>(CursorWindow.java:108)
2019-04-10 16:39:17.067 W/System.err:     at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
2019-04-10 16:39:17.067 W/System.err:     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
2019-04-10 16:39:17.067 W/System.err:     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
2019-04-10 16:39:17.067 W/System.err:     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
2019-04-10 16:39:17.069 W/System.err:     at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
2019-04-10 16:39:17.069 W/System.err:     at io.horizontalsystems.bankwallet.core.storage.RatesDao_Impl$5.call(RatesDao_Impl.java:198)
2019-04-10 16:39:17.069 W/System.err:     at io.horizontalsystems.bankwallet.core.storage.RatesDao_Impl$5.call(RatesDao_Impl.java:187)
2019-04-10 16:39:17.069 W/System.err:     at android.arch.persistence.room.RxRoom$4.apply(RxRoom.java:111)
```
We create HttpClient for each request.
https://github.com/square/okhttp/issues/1943#issuecomment-151024020

**Comment by rafaelekol** [comment]
Crash log:

```
OkHttp: <-- HTTP FAILED: java.net.SocketException: socket failed: EMFILE (Too many open files)
2019-04-10 16:39:17.059 W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
2019-04-10 16:39:17.060 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-04-10 16:39:17.060 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-04-10 16:39:17.060 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-04-10 16:39:17.062 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-04-10 16:39:17.062 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-04-10 16:39:17.064 W/System.err: Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
2019-04-10 16:39:17.064 W/System.err:     at android.database.CursorWindow.<init>(CursorWindow.java:108)
2019-04-10 16:39:17.067 W/System.err:     at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
2019-04-10 16:39:17.067 W/System.err:     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
2019-04-10 16:39:17.067 W/System.err:     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
2019-04-10 16:39:17.067 W/System.err:     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
2019-04-10 16:39:17.069 W/System.err:     at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
2019-04-10 16:39:17.069 W/System.err:     at io.horizontalsystems.bankwallet.core.storage.RatesDao_Impl$5.call(RatesDao_Impl.java:198)
2019-04-10 16:39:17.069 W/System.err:     at io.horizontalsystems.bankwallet.core.storage.RatesDao_Impl$5.call(RatesDao_Impl.java:187)
2019-04-10 16:39:17.069 W/System.err:     at android.arch.persistence.room.RxRoom$4.apply(RxRoom.java:111)
```
We create HttpClient for each request.
https://github.com/square/okhttp/issues/1943#issuecomment-151024020
